Release target improvements.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -19,17 +19,25 @@ ACLOCAL_AMFLAGS = -I m4 -I gl/m4
 
 DISTCHECK_CONFIGURE_FLAGS = --enable-gtk-doc
 
+EXTRA_DIST = 70-u2f.rules BLURB cfg.mk macosx.mk windows.mk
+
 # Release
 
 ChangeLog:
 	cd $(srcdir) && git2cl > ChangeLog
 
-release:
+release: my-release
+my-release:
+	@if test ! -d "$(YUBICO_WWW_REPO)"; then \
+		echo "www repo not found!"; \
+		echo "Make sure that YUBICO_WWW_REPO is set"; \
+		exit 1; \
+	fi
 	@head -3 $(srcdir)/NEWS | \
 		grep -q "Version $(VERSION) .released `date -I`" || \
 		(echo 'error: Update date/version in $(srcdir)/NEWS'; exit 1)
 	rm -f $(srcdir)/ChangeLog
-	make ChangeLog distcheck
+	make ChangeLog syntax-check distcheck
 	make -f windows.mk VERSION=$(VERSION)
 	gpg --detach-sign $(PACKAGE)-$(VERSION).tar.gz
 	gpg --detach-sign $(PACKAGE)-$(VERSION)-win32.zip
@@ -38,3 +46,7 @@ release:
 	cd $(srcdir) && git push
 	cd $(srcdir) && git tag -s -m "$(PACKAGE) $(VERSION)" $(PACKAGE)-$(VERSION)
 	cd $(srcdir) && git push --tags
+	$(YUBICO_WWW_REPO)/publish $(PACKAGE) $(VERSION) $(PACKAGE)-$(VERSION).tar.gz*
+	$(YUBICO_WWW_REPO)/publish $(PACKAGE) $(VERSION) $(PACKAGE)-$(VERSION)-win32.zip
+	$(YUBICO_WWW_REPO)/publish $(PACKAGE) $(VERSION) $(PACKAGE)-$(VERSION)-win64.zip
+	rsync -a $(srcdir)/gtk-doc/html/ $(YUBICO_WWW_REPO)/libykneomgr/gtk-doc/
